package com.example.healme.firebase.shenagingans

/**
 * Data class representing a single medical history (a previous operation) of a patient
 *
 * @property id The identifier of the medical history generated by firebase.
 * @property patientId The identifier of the patient who the medical history belongs to.
 * @property doctorId The identifier of the doctor who created the medical history.
 * @property content The content of the medical history.
 * @property timestamp The timestamp of the medical history.
 */
data class MedicalHistory (val id: String = "",
                          val patientId: String = "",
                          val doctorId: String = "",
                          val content: String = "",
                          val timestamp: String = ""

) {

    companion object {
        /**
         * Creates a MedicalHistory object from firebase.
         *
         * @param data The data belonging to a MedicalHistory.
         * @return A MedicalHistory object.
         */
        fun fromMap(data: Map<String, Any?>): MedicalHistory {
            return MedicalHistory(
                id = data["id"] as? String ?: "",
                patientId = data["patientId"] as? String ?: "",
                doctorId = data["doctorId"] as? String ?: "",
                content = data["content"] as? String ?: "",
                timestamp = data["timestamp"] as? String ?: ""
            )
        }
    }
}