package com.example.healme.data.models.user

/**
 * Data class representing a Patient
 *
 * @property medicalHistory The medical history of the patient.
 * @property messages The messages sent to the patient.
 * @property id The identifier of the Patient generated by firebase.
 * @property email The email address of the Patient.
 * @property name The name of the Patient.
 * @property surname The surname of the Patient.
 * @property dateOfBirth The date of birth of the Patient.
 */
class Patient(
    id: String = "",
    email: String = "",
    name: String = "",
    surname: String = "",
    dateOfBirth: String = "",
    fcmToken: String? = null
) : User(id, email, name, surname, dateOfBirth, fcmToken) {

    companion object {

        /**
         * Creates a Patient object from firebase.
         *
         * @param data The data belonging to a Patient.
         * @return A Patient object.
         */
        fun fromMap(data: Map<String, Any?>): Patient {
            return Patient(
                id = data["id"] as? String ?: "",
                name = data["name"] as? String ?: "",
                email = data["email"] as? String ?: "",
                surname = data["surname"] as? String ?: "",
                dateOfBirth = data["dateOfBirth"] as? String ?: "",
                fcmToken = data["fcmToken"] as? String
            )
        }
    }

    /**
     * Returns the name of the collection for Patient objects in Firebase.
     *
     * @return "patients"
     */
    override fun getCollectionName(): String {
        return "patients"
    }

    /**
     * Returns the stringified representation of the Patient.
     *
     * @return The name and surname of the Patient.
     */
    override fun toString(): String {
        return "${super.name} ${super.surname}"
    }
}
