package com.example.healme.user

/**
 * Data class representing an Admin.
 *
 * @property id The identifier of the Admin generated by firebase.
 * @property email The email address of the Admin.

 */
class Admin ( id: String = "",
                   email: String = "",
                   name: String = "",
                   surname: String = "",
                   dateOfBirth: String = "",
) :  User(id, email, name, surname, dateOfBirth)  {
    companion object {
        /**
         * Creates an Admin object from firebase.
         *
         * @param details The data belonging to an Admin.
         * @return An Admin object.
         */
        fun fromMap(data: Map<String, Any?>): Admin {
            return Admin(
                id = data["id"] as? String ?: "",

                email = data["email"] as? String ?: ""
            )
        }
    }
    /**
     * Returns the name of the collection for Admin objects in Firebase.
     *
     * @return "admins"
     */
    override fun getCollectionName(): String {
        return "admins"
    }
}
